steps:
  - id: "build image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
          "build",
          "-t",
          "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_PR_NUMBER}-${SHORT_SHA}",
          ".",
      ]

  - id: "push image"
    name: "gcr.io/cloud-builders/docker"
    args:
      [
          "push",
          "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_PR_NUMBER}-${SHORT_SHA}",
      ]

  - id: "deploy revision with tag"
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      [
          "beta",
          "run",
          "deploy",
          "${PROJECT_ID}-red",
          "--platform",
          "managed",
          "--region",
          "us-central1",
          "--image",
          "gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:${_PR_NUMBER}-${SHORT_SHA}",
          "--tag",
          "pr-${_PR_NUMBER}",
          "--no-traffic",
      ]

  - id: "link revision on pull request"
    name: "gcr.io/${PROJECT_ID}/deployment-previews" # our custom builder
    args:
      [
          "set",
          "--project-id",
          "${PROJECT_ID}",
          "--region",
          "us-central1",
          "--service",
          "${_SERVICE_NAME}",
          "--pull-request",
          "${_PR_NUMBER}",
          "--repo-name",
          "${_GITHUB_REPO}",
          "--commit-sha",
          "${SHORT_SHA}",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _SERVICE_NAME: previews
  _GITHUB_REPO: $(pull_request.pull_request.head.repo.full_name)
